### PR TITLE
Support the discord:// protocol in buttons

### PR DESCRIPTION
**Pull request by CottageDwellingCat**
Support the `discord://` protocol in buttons, as per https://github.com/discord/discord-api-docs/discussions/3347,
this pr creates the method `UrlValidation.ValidateButton` and uses it when validating button URLs.

### CODE REVIEW

**Comment by INikonI** [comment]
I think it can be more easy, without code copy paste. And may be need documentation 🤔
```cs
public static bool ValidateButton(string url)
{
    if (!Validate(url) && !url.StartsWith("discord://", StringComparison.OrdinalIgnoreCase))
        throw new InvalidOperationException($"Url {url} must be include its protocol (either HTTP, HTTPS, or DISCORD)");
    return true;
}
```

**Comment by CottageDwellingCat** [comment]
Thank you, that is a much cleaner way to do it 😄. It might make scene to also check if it's null or empty, so the method can still return false; as well as make the error messages more readable.
```cs
public static bool ValidateButton(string url)
{
    if(string.IsNullOrEmpty(url))
           return false;
    if (!validate(url) || !url.StartsWith("discord://", StringComparison.OrdinalIgnoreCase))
        throw new InvalidOperationException($"The url {url} must include a protocol (either HTTP, HTTPS, or DISCORD)");
    return true;
}
```

**Comment by INikonI** [comment]
Null check already in validate method

**Comment by CottageDwellingCat** [comment]
yes, but it would throw an error instead of just returning false like validate does.

**Comment by INikonI** [comment]
Oh, I right now understand, `validate` method throw it error before `validateButton` .-.

**Comment by INikonI** [comment]
in that case, i think, no need edit anything

**Review by INikonI — APPROVED** [review]

**Review by quinchs — APPROVED** [review]

**Pull request merged**
