### PR TITLE
Added default permission to context command builders

### PR DESCRIPTION
**Pull request by Cenngo**
This PR adds the missing default permission option to the Context Command builders

### CODE REVIEW

**Comment by quinchs** [comment]
Please pull and fix related changes to ratelimits for this PR

**Comment by Cenngo** [comment]
> Please pull and fix related changes to ratelimits for this PR

This PR is ahead of release/3.x,  feature/internal-ratelimiting and feature/ratelimit-callbacks. There is nothing to pull. Are you referring to feature/cache-providers.

**Comment by Cenngo** [comment]
> Please pull and fix related changes to ratelimits for this PR

Didn't you merge the feature/internal-ratelimiting to the release branch 3 days ago? This was based on that. Nvm, there are too many conflicting commits, i will just create a brand new PR(#155).

**Comment by quinchs** [comment]
The new ratelimit stuff was shot to wack and broke alot of things

**Pull request closed without merging**
