### PR TITLE
Adding New Extensions 

### PR DESCRIPTION
**Pull request by ghost**
### EmbedFieldBuilderExtensions
**Hello 👋**, i added a new Extension for EmbedFieldBuilder, its can make the codes more beautiful & clean .

### with Extension
```csharp
       new EmbedBuilder()
        {
            Title = "",
            Description = "",
            Fields = new List<EmbedFieldBuilder>()
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
        }.Build();

```

### Without Extension

```csharp
 new EmbedBuilder()
        {
            Title = "",
            Description = "",
            Fields = new List<EmbedFieldBuilder>()
            {
                 new EmbedFieldBuilder()
                 {
                    IsInline=true,
                    Name="Name",
                    Value ="valuse"
                 },
                 new EmbedFieldBuilder()
                {
                    IsInline=true,
                    Name="Name",
                    Value ="valuse"
                },
                  new EmbedFieldBuilder()
                {
                    IsInline=true,
                    Name="Name",
                    Value ="valuse"
                },
                   new EmbedFieldBuilder()
                {
                    IsInline=true,
                    Name="Name",
                    Value ="valuse"
                },
                    new EmbedFieldBuilder()
                {
                    IsInline=true,
                    Name="Name",
                    Value ="valuse"
                },
            }
        }.Build();

```
        
### Format Extensions (User, Channel, Role Tags + Emote)
+ Format Extensions (User, Channel, Role Tags + Emote)

### CODE REVIEW

**Comment by quinchs** [comment]
Theres already a `EmbedBuilder.WithFields` and `EmbedBuilder.AddField` method.

**Comment by ghost** [comment]
> Theres already a `EmbedBuilder.WithFields` and `EmbedBuilder.AddField` method.

So is possible to making fields like that (in EmbedBuilder blocks) or something for adding Filed to Filed List.

```csharp
 new EmbedBuilder()
        {
            Title = "",
            Description = "",
            Fields = new List<EmbedFieldBuilder>()
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
            .WithField("Name", "Value", false)
        }.Build();
        ```

**Comment by quinchs** [comment]
It would be
```cs
new EmbedBuilder()
    .WithTitle("Hello World!")
    .AddField("Field Title", "Field content")
```

**Comment by ghost** [comment]
> It would be
> 
> ```cs
> new EmbedBuilder()
>     .WithTitle("Hello World!")
>     .AddField("Field Title", "Field content")
> ```

yes, i see, but its can be good still for adding fields in the body, also i added some Formats, check them too.
anyways if was good, merge it, if not reject.

**Comment by quinchs** [comment]
All the additions that your making already exist in an easier form. I just dont see a need for them, sorry.

**Pull request closed without merging**
