### PR TITLE
URL validation and error handling

### PR DESCRIPTION
**Pull request by Zeiin**
Currently very primitive and straightforward changes to verify that a URL passed in to any of the various url-adjacent fields in embeds and components are well formatted (this also checks for protocol).

### CODE REVIEW

**Review by quinchs — APPROVED** [review]

**Comment by d4n3436** [comment]
Hmm I'm not sure if using `Uri.IsWellFormedUriString()` as url validation is a good idea.
It was removed from Discord.Net in this [pull request](https://github.com/discord-net/Discord.Net/pull/1778) because it's known to have bugs.

**Comment by Zeiin** [comment]
I can go back to my original validation of just checking for protocol if that's the case, since that's really the only error people really see often enough to care about. 

For reference it'd just be validating that any non-empty url strings include "http://" or "https://". Alternatively I can look into better url validation solutions as a whole if that wouldn't suffice.

**Comment by Zeiin** [comment]
Reading up on discord docs: Only image-based urls require http/s, but most other protocols also fail to work unless used with markdown text (i.e steam:// would work as text, but not as an embed url).

Do we want to impose an http/https restriction on every url or just what's labeled in the docs?

**Comment by Zeiin** [comment]
For reference: Zeiin@1e49a73 is what it'd look like.

**Comment by d4n3436** [comment]
> For reference: [Zeiin/Discord.Net-Labs@1e49a73](https://github.com/Zeiin/Discord.Net-Labs/commit/1e49a73) is what it'd look like.

Looks good enough. I would create a helper method that simplifies the process of checking and throwing exceptions:

```c#
private void ValidateUrl(string url, string paramName)
{
    if (url != null && !(url.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
    || url.StartsWith("https://", StringComparison.OrdinalIgnoreCase)))
    {
        throw new InvalidOperationException($"{paramName} must include its protocol (either HTTP or HTTPS).");
    }
    
    // Some better validation
}
```

**Comment by Zeiin** [comment]
Yeah I'll do that somewhere and use the same method in both embed and component builders. 

Should I call it anytime a url attribute is added, or just stick the call in the respective build methods? Logically there's nothing wrong with setting an embed or link button's url to one without a protocol, it's only upon building/sending it that it's an issue.

**Pull request merged**
