### PR TITLE
Fix Application Command Validation

### PR DESCRIPTION
**Pull request by Cenngo**
This PR adds additional command validation steps aiming to give users more descriptive runtime exceptions and reduce the number of `Invalid Form Body` exception encounters.

### CODE REVIEW

**Review by quinchs — APPROVED** [review]

**Comment by quinchs** [comment]
Why is this a draft?

**Comment by Cenngo** [comment]
For some reason, even though i switched to SlashCommandBuilder, SlashCommandBuilder.Name.set is still not throwing the intended error.

**Comment by Cenngo** [comment]
ofc, SlashCommandBuilder doesnt check if there is any uppercase letters in the command name. We should implement that in the core library.

**Comment by quinchs** [comment]
Do you want to make a PR for it?

**Comment by Cenngo** [comment]
> Do you want to make a PR for it?

Yes, will do that tomorrow.

**Comment by quinchs** [comment]
Is this ready for review now?

**Comment by Cenngo** [comment]
> Is this ready for review now?

Everything seems to be in order.

**Pull request merged**
