### PR TITLE
Changes on Emote/Emoji and SelectMenu

### PR DESCRIPTION
**Pull request by INikonI**
In this request, the name of the `Emote` was changed to `CustomEmoji` and all the names of the `Emote` (for example, `IEmote`) were changed to `Emoji` (that is, `IEmoji`), because these are more correct and understandable names.

`Emoji` class now has a static `TryParse` and `Parse` methods and the constructor now has an internal modifier.

Label was removed from `SelectMenuBuilder`, because it does not exist in the api, and `Disabled` was added to `SelectMenu` classes and builders.

### CODE REVIEW

**Comment by quinchs** [comment]
I would hold off on modifying the DNET base stuff as changing names like that will cause anyone whos going to update to have a lot of errors if they are using emotes/emojis. I would only merge that if it was coming from dnet.

On the other hand, the changes to the SelectMenus look good!

**Comment by INikonI** [comment]
Maybe undo renaming Emote, but save emoji parsing?

**Comment by quinchs** [comment]
> Maybe undo renaming Emote, but save emoji parsing?

Yeah, the addition of `TryParse` is fine, just dont rename any of the emote/emojis stuff as i can already see the `Unknown Reference` exceptions in the issues tab

**Comment by INikonI** [comment]
I undone renaming. I also wanted to ask, I noticed that the Components property of message interfaces is a collection with `IMessageComponent`, why it not a `ActionRowComponent`?

**Comment by quinchs** [comment]
> I undone renaming. I also wanted to ask, I noticed that the Components property of message interfaces is a collection with `IMessageComponent`, why it not a `ActionRowComponent`?

Discord might add different component roots, and those can be added under the interface

**Pull request merged**
