### PR TITLE
Fixed url validation to be neater and not utilize IsWellFormatted

### PR DESCRIPTION
**Pull request by Zeiin**
Title, pretty simple change.

### CODE REVIEW

**Review by quinchs — DISMISSED** [review]

**Comment by quinchs** [comment]
Please fix the merge conflicts by pulling then pushing to your fork

**Comment by Zeiin** [comment]
Merge conflicts resolved, retesting real quick to ensure no issues.

**Comment by Zeiin** [comment]
Testing looks good 👍

**Comment by Zeiin** [comment]
Didn't mean to merge my branches before the PR went through. Let me fix that

**Pull request merged**
